// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oinvtlxqizlcaipvilnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbnZ0bHhxaXpsY2FpcHZpbG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDM5NzksImV4cCI6MjA3Njg3OTk3OX0.kHQb0_X2ynqGazipHZ5WBCGsLLOho0yPO3eoIfNZ7LM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);